#!/bin/sh

#Define Parameters
bridge=$1 # br0
prefix=$2 # tap_

tag="TapToBridge"
sleep 1

for i in 1 2 4 4 6 8 8 8
do
    modprobe tun
    sleep $i
    taps=`ifconfig | grep -E "$prefix[[:alnum:]_]+ +Link " -o | grep -E "$prefix[[:alnum:]_]+" -o`
    if [ -n "$taps" ]
    then
        sleep 1
        taps=`ifconfig | grep -E "$prefix[[:alnum:]_]+ +Link " -o | grep -E "$prefix[[:alnum:]_]+" -o`
        logger -t $tag -s "Interface [$taps] Found."
        break
    fi
done

if [ -z "$taps" ]
then
    logger -t $tag -s "No Interfaces Found."
    exit 1
fi

#for tap in $taps
#do
#    res=`brctl addif $bridge $tap 2>&1`
#    if [ -z "$res" ]
#    then
#        logger -t $tag -s "Interface [$tap] Added to [$bridge]"
#    else
#        logger -t $tag -s "$res"
#    fi
#done

#brctl setportprio br0 tap_br0_vpn 1

#brctl delif br0 tap_br0_hkt
#brctl delif br0 tap_br0_hk1901

/jffs/userscripts/linkagg bond0 tap_br0_hkt tap_br0_hk1901
brctl addif br0 bond0
#brctl setportprio br0 bond0 1000

#brctl setportprio br0 tap_br0_hkt 1
#brctl setportprio br0 tap_br0_hk1901 100