#!/bin/sh

#Define Parameters
bridge=$1 # br0
prefix=$2 # tap_

$tag="TapToBridge"
sleep 1

for i in 1 2 4 4 6 8 8 8
do
    modprobe tun
    sleep $i
    taps=`ifconfig | grep -E "$prefix[[:alnum:]]+ +Link " -o | grep -E "$prefix[[:alnum:]]+" -o`
    if [ -n "$taps" ]
    then
        sleep 1
        taps=`ifconfig | grep -E "$prefix[[:alnum:]]+ +Link " -o | grep -E "$prefix[[:alnum:]]+" -o`
        logger -t $tag -s "Interface [$taps] Found."
        break
    fi
done

if [ -z "$taps" ]
then
    logger -t $tag -s "No Interfaces Found."
    exit 1
fi

for tap in $taps
do
    res=`brctl addif $bridge $tap 2>&1`
    if [ -z "$res" ]
    then
        logger -t $tag -s "Interface [$tap] Added to [$bridge]"
    else
        logger -t $tag -s "$res"
    fi
done