#!/bin/sh

# Exit if /tmp/addroute.lockfile exists
[ -f /tmp/china_ips_route.lockfile ] && exit

# Create lock file, sleep 1 sec and verify lock
echo $$ > /tmp/china_ips_route.lockfile
sleep 1
[ "x$(cat /tmp/china_ips_route.lockfile)" == "x"$$ ] || exit

#Define Parameters
dns_server="http://119.29.29.29/d?dn="
default_interface=ppp0

hk_gateway=172.30.3.1

frp_server=172.30.3.5

my_domains="hk.geoe.cn hk2.geoe.cn hkt.geoe.cn hkt2.geoe.cn gzt2.geoe.cn"
non_china_ips=/jffs/userscripts/non_china_ips

tag="DirectRoutes"

echo `date`

for i in 1 2 3 4 5 6 7 8 8 8 16 16 16 32 32 32 64 64 64
do
    ppp0gw=`ip addr show dev $default_interface | grep -e "peer [0-9\.]\+" -o | grep -e "[0-9\.]\+" -o`
    if [ -n $ppp0gw ]; then
        break
    fi
    logger -t $tag -s "Could not find the default gateway for [$default_interface]. Try again in $i seconds."
    sleep $i
done

if [ -z $ppp0gw ]; then
    logger -t $tag -s "Could not find the default gateway for [$default_interface]. Exit!"
    exit 1
fi

logger -t $tag -s "Default Gateway [$ppp0gw] for Interface [$default_interface] was Found."

addHostRoute(){
    domain=$1
    gateway=$ppp0gw
    logger -t $tag -s "Add route record for $domain"
    for i in 1 2 3 4 5 6 7 8 9
    do
        for j in 1 2 3 4 5 6 7 8 9
        do
            IPs=`curl -s ${dns_server}${domain} | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" -o`
            if [ -n "$IPs" ]; then
                logger -t $tag -s "Get $domain ip: $IPs"
                break
            fi
            logger -t $tag -s "Could NOT Get $domain IP. Try again in $j seconds."
            sleep $j
        done
        errmsg=""
        for IP in $IPs
        do
            logger -t $tag -s "Remove Current Route for $IP"
            ip route del ${IP}
            logger -t $tag -s "Add Route for $IP with gateway $gateway"
            ip route add ${IP}/32 via $gateway
            tmpExist=`route -n | grep "$IP"`
            if [ -n "$tmpExist" ]; then
                logger -t $tag -s "Route for $IP with gateway $gateway Exist - $tmpExist"
            else
                errmsg="${errmsg} Route for $IP with gateway $ppp0gw NOT Exist."
            fi
        done

        if [ -z "$errmsg" ]; then
            break
        fi
        
        logger -t $tag -s "${errmsg}. Try again in $i seconds"
        sleep $i
    done
}

for my_domain in ${my_domains}
do
    addHostRoute $my_domain
done

#check HK gateway connectivity
for i in 1 2 3 4 5 6 7 8 8 8 16 16 16 32 32 32 64 64 64
do
    res=`ping -c 1 -W 3 ${hk_gateway} | grep "bytes from ${hk_gateway}: seq=0 ttl="`
    if [ -n "${res}" ]; then
        logger -t $tag -s "${hk_gateway} connected."
        break
    fi
    logger -t $tag -s "${hk_gateway} unreachable. Try again in $i seconds"
    sleep $i
done
if [ -z "${res}" ]; then
    logger -t $tag -s "${hk_gateway} unreachable. Exit!"
    exit 1
fi

echo `date`
logger -t $tag -s "Add Batch Route to Hong Kong Server for IPs Outside China Regions"

logger -t $tag -s "Remove all existing ips route to the Gateway $hk_gateway"
ip route | grep " via $hk_gateway " > /tmp/existing_routes_via_gateway
sed -i -E 's/([[:print:]]+)/route del \1/g' /tmp/existing_routes_via_gateway
ip -batch /tmp/existing_routes_via_gateway
rm /tmp/existing_routes_via_gateway

logger -t $tag -s "Add all non_china_ips route to the Gateway $hk_gateway"
sed -E "s/([0-9\./]+)/route add \1 via $hk_gateway/g" "$non_china_ips" > /tmp/non_china_ips_routes
ip -batch /tmp/non_china_ips_routes
rm /tmp/non_china_ips_routes

logger -t $tag -s "FINFISHED: Add all non_china_ips route to the Gateway $hk_gateway"

#logger -t $tag -s "Add 10.0.0.0 route to $hk_gateway"
#ip route add 10.0.0.0/8 via $hk_gateway

#Remote Desktop to Company Computer
logger -t $tag -s "Reroute WSP RDP to frp_server ($frp_server)"
iptables -t nat -D PREROUTING -p tcp -d 10.35.32.92 --dport 3389 -j DNAT --to-destination $frp_server:6389
iptables -t nat -I PREROUTING -p tcp -d 10.35.32.92 --dport 3389 -j DNAT --to-destination $frp_server:6389

#SMB to Company Computer
logger -t $tag -s "Reroute WSP Samba to frp_server ($frp_server)"
iptables -t nat -D PREROUTING -p tcp -d 10.35.32.92 --dport 445 -j DNAT --to-destination $frp_server:6445
iptables -t nat -I PREROUTING -p tcp -d 10.35.32.92 --dport 445 -j DNAT --to-destination $frp_server:6445
iptables -t nat -D PREROUTING -p tcp -d 10.35.50.46 --dport 445 -j DNAT --to-destination $frp_server:6446
iptables -t nat -I PREROUTING -p tcp -d 10.35.50.46 --dport 445 -j DNAT --to-destination $frp_server:6446
iptables -t nat -D PREROUTING -p tcp -d 10.35.50.86 --dport 445 -j DNAT --to-destination $frp_server:6447
iptables -t nat -I PREROUTING -p tcp -d 10.35.50.86 --dport 445 -j DNAT --to-destination $frp_server:6447

iptables -t nat -D POSTROUTING -p tcp -d $frp_server -m multiport --dport 6000:6999 -j MASQUERADE
iptables -t nat -I POSTROUTING -p tcp -d $frp_server -m multiport --dport 6000:6999 -j MASQUERADE


echo `date`

rm /tmp/china_ips_route.lockfile
